version: '3.8'
services:
  apache:
    build: .docker/apache
    container_name: app_apache
    ports:
      - 8181:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/app
    depends_on:
      - php

  database:
    image: mysql:5.7
    container_name: app_database
    restart: always
    ports:
        - 8383:3306
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_db_user
      MYSQL_PASSWORD: app_db_password

  php:
    build: .docker/php
      context: .
      args: php_version
    working_dir: /home/wwwroot/app
    container_name: app_php
    volumes:
      - .:/home/wwwroot/app
    environment:
      - maildev_host=app_maildev
    depends_on:
      - maildev
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    ports:
      - 8585:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_db_user
      MYSQL_PASSWORD: app_db_password
    links:
      - database
    depends_on:
      - database

  maildev:
    image: djfarrelly/maildev
    container_name: app_maildev
    ports:
      - 8787:80
